config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  post 'create_users' => 'welcome#create_users'
  post 'products' => 'welcome#create_products'

  get 'users' => 'welcome#users'
  get 'users/:id' => 'welcome#show_user'
  get 'products' => 'welcome#products'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @product = Product.new
  end

  def users
    @users = User.all
  end

  def products
    @products = Product.all
  end

  def create_users
    User.create(name: params[:name], age: params[:age])
    redirect_to users_path
  end

  def create_products
    Product.create(product_params)
    redirect_to products_path
  end

  def show_user
    @user = User.find(params[:id])
  end

  private

  def product_params
    params.require(:product).permit(:name, :price, :quantity)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LackOScaff</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Home Page</h1>


<h3>Create a User</h3>

<%= form_tag create_users_path do %>
  <%= text_field_tag :name, nil, placeholder: "Your Name" %><br />
  <%= number_field_tag :age, nil, placeholder: "Your Age" %><br />
  <%= submit_tag 'Create User' %>
<% end %>


<%= form_for @product do |f| %>
  <%= f.text_field :name, placeholder: 'Product Name' %><br />
  <%= f.number_field :price, placeholder: 'Product Price' %><br />
  <%= f.number_field :quantity, placeholder: 'Product Qty' %><br />
  <%= f.submit %>
<% end %>

app/views/welcome/products.html.erb
<h1>All Products</h1>

<table>
  <tr>
    <th>Name</th><th>Price</th><th>Quantity</th>
  </tr>

  <% @products.each do |product| %>
  <tr>
    <td><%= product.name %></td>
    <td><%= product.price %></td>
    <td><%= product.quantity%></td>
  </tr>
  <% end %>
</table>

<%= link_to 'Back', root_path %>

app/views/welcome/show_user.html.erb
<h2><%= @user.name %>'s Profile</h2>

<p>Age: <%= @user.age %></p>

app/views/welcome/users.html.erb
<h1>All The Users</h1>

<ul>
  <% @users.each do |user| %>
  <li>
    Name: <%= user.name %>; Age: <%= user.age %>
  </li>
  <% end %>
</ul>

<%= link_to "Return to Index", root_path %>